[package]
name = "everest"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true

[dependencies]
argh.workspace = true
rumqttc.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
