[package]
name = "everest"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.10"
rumqttc = "0.22.0"
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.103"
thiserror = "1.0.44"
